language: node_js
sudo: false
notifications:
  email: false
node_js:
- 6.9.1
env:
- DB=memory
script:
- yarn test
cache:
  yarn: true
  directories: node_modules
after_success:
- yarn run semantic-release
- bash <(curl -s https://codecov.io/bash)
